# Generated by Django 5.2.7 on 2025-10-09 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_admin_clave_admin_agente_clave_agente_usuario_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('prioridad', models.CharField(default='Media', max_length=50)),
                ('estado', models.CharField(default='Abierto', max_length=50)),
                ('responsable', models.CharField(max_length=150)),
                ('archivo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_dataurl', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
