# Generated by Django 5.0.2 on 2025-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='Nuevo', max_length=50),
        ),
    ]
