# Generated by Django 5.0.2 on 2025-12-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
