# Generated by Django 5.0.2 on 2025-12-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_ticket_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(limit_choices_to={'rol': 'agente'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chat_agente', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_chat', to='cuentas.ticket')),
                ('usuario', models.ForeignKey(limit_choices_to={'rol': 'usuario'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultima_actividad'],
                'unique_together': {('usuario', 'agente')},
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_agente', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='cuentas.conversacionchat')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
