# Generated by Django 5.0.2 on 2025-12-03 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ticket_assigned', 'Ticket Asignado'), ('ticket_response', 'Respuesta en Ticket'), ('ticket_closed', 'Ticket Cerrado'), ('user_registered', 'Usuario Registrado')], max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(blank=True, default='fa-bell', max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
